sudo: false

language: node_js
node_js:
  - 8
  - node
env:
  - CXX=g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

before_script:
  - make deps
  - gcc travis_bind.c -std=c99 -o travis_bind
  - ./travis_bind
script:
  - make test
  - make itest
  - make lint
notifications:
  email:
    - phihag@phihag.de

